ALTER TABLE "LessonBlock" ADD COLUMN "origin" TEXT NOT NULL DEFAULT 'DESIGN_REQUIRED';
ALTER TABLE "LessonBlock" ADD COLUMN "justification" TEXT NOT NULL DEFAULT '';
ALTER TABLE "LessonBlock" ADD COLUMN "purposeLink" TEXT NOT NULL DEFAULT '';
